apiVersion: v2
name: telecms
description: none

type: application
version: 1.2.2
appVersion: "v1.2.2"

dependencies:
  - name: postgresql
    version: "11.1.3"
    repository: "https://charts.bitnami.com/bitnami"
