apiVersion: v1
kind: Service
metadata:
  name: telecms-lb
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: <replace-your-resource-group>
    service.beta.kubernetes.io/azure-dns-label-name: telecms
spec:
  type: LoadBalancer
  loadBalancerIP: <replace-your-public-ip-here>
  selector:
    app: telecms-ce
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
