apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: telecms
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: telecms
  minReplicas: { { .Values.apps.telecms.hpa.min } }
  maxReplicas: { { .Values.apps.telecms.hpa.max } }
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageValue: { { .Values.apps.telecms.hpa.threshhold.cpu } }
    - type: Resource
      resource:
        name: memory
        targetAverageValue: { { .Values.apps.telecms.hpa.threshhold.ram } }
