apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.apps.telecms.secret.name }}"
type: Opaque
data:
  pg_user: { { .Values.apps.telecms.secret.data.pg_user | b64enc | quote } }
  pg_password:
    { { .Values.apps.telecms.secret.data.pg_password | b64enc | quote } }
  pg_db: { { .Values.apps.telecms.secret.data.pg_db | b64enc | quote } }
  lockbox_key:
    { { .Values.apps.telecms.secret.data.lockbox_key | b64enc | quote } }
  secret_key_base:
    { { .Values.apps.telecms.secret.data.secret_key_base | b64enc | quote } }
