apiVersion: v1
kind: Service
metadata:
  name: telecms
spec:
  type: { { .Values.apps.telecms.service.type } }
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: telecms
